version: '3.8'

services:
  server:
    build: ./server
    volumes:
      - ./server/simplesamlphp:/var/www/simplesamlphp
      - ./server/html:/var/www/html

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./server/html:/var/www/html
      - ./server/simplesamlphp:/var/www/simplesamlphp
    depends_on:
      - server
